### ISSUE TITLE
Handling date time fields

### ISSUE THREAD

**Issue by rajeshg** [kiliman/epic-stack-time-zone#1]
@kiliman Thanks for adding the timezone client hints for epic-stack. 

Handle date-time inputs (with a form) is a common use case that has often caused trouble (at least for me). If possible, can you add an example for this. Something like 
1. Add `publishedAt DateTime` to schema.prisma
2. Edit note-editor to add a publish datetime. 
3. User selects a time in his local time.
4. Server persists it in a uniform way (something like a ISO/UTC time)
5. When any user request a list of notes, how do we make sure that the users see the correct date in their respective timezone? So  a user in EST should see the EST time and a user in PST will see the date time in PST.

**Comment by kiliman** [comment]
Ok, I didn't add a `publishedAt` column. I just used the existing `updatedAt`.

But I now show the correct "published" date/time on the note page.

<img width="736" alt="image" src="https://github.com/kiliman/epic-stack-time-zone/assets/47168/7d8701bc-0c85-4f88-a56b-950c8daf2366">

**Comment by kiliman** [comment]
BTW: I changed my time zone from Eastern to Pacific, and it displays the correct time.
<img width="799" alt="image" src="https://github.com/kiliman/epic-stack-time-zone/assets/47168/516ccc71-deba-4d09-82eb-77c6d5339b4c">
